services:
  jobserver:
    image: ghcr.io/mprov-ng/mprov-jobserver:dev
    restart: unless-stopped
    volumes:
      - /home/export:/export
    env_file:
      - stack.env
    ports:
      - 8080:8080
    user: ${UID:-0}:${GID:-0}
    
    
volumes:
  jobserver-data: