name: Python Module CI and Docker build.
on:
  release: 
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout 
        uses: actions/checkout@v2
      
      - name: Setup Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
        
      - name: Install Dependancies
        run: |
          sudo apt-get update
          sudo apt-get install libparted-dev libparted2
          python -m pip install --upgrade pip
          pip install setuptools build
          pip install -r requirements.txt
          ln -sf /usr/bin/python /usr/bin/python3
      
      - name: Parse the version
        id: vars
        run: echo tag=$(echo ${GITHUB_REF:10}) >> $GITHUB_ENV

      - name: Build Package
        run: |
          echo "$tag" > VERSION
          python -m build
      
      - name: Publish Package to Pypi
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - 
        name: Setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - 
        name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT }}

      - 
        name: Build the mProv Jobserver Docker Image
        uses: docker/build-push-action@v2
        with:
          tags: |
            ghcr.io/mprov-ng/mprov-jobserver:${{ env.tag }}
            ghcr.io/mprov-ng/mprov-jobserver:latest
          push: true    
